TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.1
  max_vel_theta: 0.9
  min_vel_theta: -0.9
  min_in_place_vel_theta: 0.2

  acc_lim_theta: 0.7
  acc_lim_x: 0.1
  acc_lim_y: 0.1

  holonomic_robot: true
  meter_scoring: true
  use_dwa: false


EBandPlannerROS:
 # Common Parameters
 xy_goal_tolerance: 0.1
 yaw_goal_tolerance: 0.05
 rot_stopped_vel: 0.01
 trans_stopped_vel: 0.01


 # Elastic Band Parameters
 eband_min_relative_overlap: 0.7
 eband_tiny_bubble_distance: 0.01
 eband_tiny_bubble_expansion: 0.01
 eband_internal_force_gain: 1.0
 eband_external_force_gain: 2.0
 num_iterations_eband_optimization: 3
 eband_equilibrium_approx_max_recursion_depth: 4
 eband_equilibrium_relative_overshoot: 0.75
 eband_significant_force_lower_bound: 0.15
 costmap_weight: 10.0
 
 # Trajectory Controller Parameters
 max_vel_lin: 0.7
 min_vel_lin: 0.1
 max_vel_th: 0.0
 min_vel_th: 0.0
 min_in_place_vel_th: 0.0
 in_place_trans_vel: 0.0
 k_prop: 4.0
 k_damp: 3.5
 max_acceleration: 0.5
 max_translational_acceleration: 0.8
 max_rotational_acceleration: 1.5
 rotation_correction_threshold: 0.5
 differential_drive: false
 bubble_velocity_multiplier: 2.0
 rotation_threshold_multiplier: 1.0
 disallow_hysteresis: false




DWAPlannerROS:
  holonomic_robot: true
  acc_lim_th: 0.0 
  acc_lim_x: 1.0 
  acc_lim_y: 1.0 


  max_vel_x: 0.4 
  min_vel_x: -0.4 

  max_vel_y: 0.4 
  min_vel_y: -0.4 

  max_trans_vel: 0.65 
  min_trans_vel: 0.1 
  max_rot_vel: 0.0 
  min_rot_vel: 0.0 

  sim_time: 1.7 
  sim_granularity: 0.025 
  goal_distance_bias: 1.0 
  path_distance_bias: 32.0 
  occdist_scale: 0.01 
  stop_time_buffer: 0.2 
  oscillation_reset_dist: 0.05 
  forward_point_distance: 0.325 
  scaling_speed: 0.25 
  max_scaling_factor: 0.2 
  vx_samples: 3 
  vy_samples: 10 
  vtheta_samples: 20 
  sim_period: 0.1 
  xy_goal_tolerance: 0.2 
  yaw_goal_tolerance: 0.17 
  rot_stopped_vel: 0.01 
  trans_stopped_vel: 0.01





TebLocalPlannerROS:
 # Trajectory
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: False
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5
    
 # Robot
 holonomic_robot: true    
 max_vel_x: 0.4
 min_vel_x: -0.4
 max_vel_x_backwards: 0.2
 max_vel_y: 0.4
 min_vel_y: -0.4
 max_vel_theta: 0.2
 min_vel_theta: 0.0
 acc_lim_x: 0.5
 acc_lim_y: 0.2
 acc_lim_theta: 0.5
 min_turning_radius: 0.0 # omni-drive robot (can turn on place!)

 footprint_model:
   type: "point"

 # GoalTolerance
 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.1
 free_goal_vel: False
    
 # Obstacles
 min_obstacle_dist: 0.25 # This value must also include our robot radius, since footprint_model is set to "point".
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_y: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_y: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1 # WE HAVE A HOLONOMIC ROBOT, JUST ADD A SMALL PENALTY
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50

 # Homotopy Class Planner
 enable_homotopy_class_planning: False
 enable_multithreading: False
 simple_exploration: False
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False
 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False



